[package]
name = "orange-book-bm"
version = "0.1.0"
compiler = "0.14.0"
entrypoint = "lib.typ"
repository = "https://github.com/profmaurilio/typst-orange-template-bm"
authors = ["Flavio Barisi, Maurilio bortolussi"]
license = "MIT-0"
description = "A book template inspired by The Legrand Orange Book of Mathias Legrand and Vel; local adaptations introduced by M.Bortolussi"
keywords = ["book"]
categories = ["book"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
